server:
  port: 9000

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    life-service-manager:
      path: /manager/**
      service-id: life-service-manager
#      http://localhost:9000/manager/govinfo/listinfo -> http://localhost:8080/govinfo/listinfo
